/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module mult4_SARSA_RUIDO_e9_SARSA_RUIDO_e9_SarsaNada_e6_SARSA_RUIDO_e9(A, B, P);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  output [7:0] P;
  wire [7:0] P;
  wire \mul_ll.pp1 ;
  wire \mul_ll.pp2 ;
  sky130_fd_sc_hd__inv_2 _32_ (
    .A(A[3]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__and2_2 _33_ (
    .A(B[1]),
    .B(A[0]),
    .X(\mul_ll.pp2 )
  );
  sky130_fd_sc_hd__and2_2 _34_ (
    .A(A[0]),
    .B(B[0]),
    .X(\mul_ll.pp1 )
  );
  sky130_fd_sc_hd__and4_2 _35_ (
    .A(B[1]),
    .B(A[0]),
    .C(A[1]),
    .D(B[2]),
    .X(_01_)
  );
  sky130_fd_sc_hd__nand4_2 _36_ (
    .A(B[1]),
    .B(A[0]),
    .C(A[1]),
    .D(B[2]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a22oi_2 _37_ (
    .A1(B[1]),
    .A2(A[1]),
    .B1(B[2]),
    .B2(A[0]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__or4b_2 _38_ (
    .A(A[3]),
    .B(_01_),
    .C(_03_),
    .D_N(B[0]),
    .X(_04_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _39_ (
    .A1_N(_01_),
    .A2_N(_03_),
    .B1(B[0]),
    .B2(_00_),
    .X(_05_)
  );
  sky130_fd_sc_hd__and2_2 _40_ (
    .A(_04_),
    .B(_05_),
    .X(P[2])
  );
  sky130_fd_sc_hd__and2_2 _41_ (
    .A(B[2]),
    .B(A[2]),
    .X(_06_)
  );
  sky130_fd_sc_hd__nand2_2 _42_ (
    .A(A[1]),
    .B(B[3]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__and4_2 _43_ (
    .A(B[1]),
    .B(B[0]),
    .C(A[3]),
    .D(A[2]),
    .X(_08_)
  );
  sky130_fd_sc_hd__nand4_2 _44_ (
    .A(B[1]),
    .B(B[0]),
    .C(A[3]),
    .D(A[2]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_2 _45_ (
    .A(B[1]),
    .B(A[3]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__or3_2 _46_ (
    .A(_07_),
    .B(_08_),
    .C(_10_),
    .X(_11_)
  );
  sky130_fd_sc_hd__o21ai_2 _47_ (
    .A1(_08_),
    .A2(_10_),
    .B1(_07_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__and3_2 _48_ (
    .A(_06_),
    .B(_11_),
    .C(_12_),
    .X(_13_)
  );
  sky130_fd_sc_hd__a21oi_2 _49_ (
    .A1(_11_),
    .A2(_12_),
    .B1(_06_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor2_2 _50_ (
    .A(_13_),
    .B(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a22o_2 _51_ (
    .A1(B[0]),
    .A2(A[3]),
    .B1(A[2]),
    .B2(B[1]),
    .X(_16_)
  );
  sky130_fd_sc_hd__and4_2 _52_ (
    .A(A[0]),
    .B(B[3]),
    .C(_09_),
    .D(_16_),
    .X(_17_)
  );
  sky130_fd_sc_hd__a22oi_2 _53_ (
    .A1(A[0]),
    .A2(B[3]),
    .B1(_09_),
    .B2(_16_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__a211o_2 _54_ (
    .A1(_02_),
    .A2(_04_),
    .B1(_17_),
    .C1(_18_),
    .X(_19_)
  );
  sky130_fd_sc_hd__and2b_2 _55_ (
    .A_N(_17_),
    .B(_19_),
    .X(_20_)
  );
  sky130_fd_sc_hd__and2b_2 _56_ (
    .A_N(_20_),
    .B(_15_),
    .X(_21_)
  );
  sky130_fd_sc_hd__xnor2_2 _57_ (
    .A(_15_),
    .B(_20_),
    .Y(P[4])
  );
  sky130_fd_sc_hd__nand2_2 _58_ (
    .A(B[3]),
    .B(A[2]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__mux2_1 _59_ (
    .A0(B[3]),
    .A1(_22_),
    .S(_09_),
    .X(_23_)
  );
  sky130_fd_sc_hd__a21boi_2 _60_ (
    .A1(_06_),
    .A2(_12_),
    .B1_N(_11_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__or2_2 _61_ (
    .A(_23_),
    .B(_24_),
    .X(_25_)
  );
  sky130_fd_sc_hd__nand2_2 _62_ (
    .A(_23_),
    .B(_24_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__nand2_2 _63_ (
    .A(_25_),
    .B(_26_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__xnor2_2 _64_ (
    .A(_21_),
    .B(_27_),
    .Y(P[5])
  );
  sky130_fd_sc_hd__and3_2 _65_ (
    .A(A[3]),
    .B(B[3]),
    .C(_09_),
    .X(_28_)
  );
  sky130_fd_sc_hd__a21oi_2 _66_ (
    .A1(_19_),
    .A2(_24_),
    .B1(_23_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__a31o_2 _67_ (
    .A1(_15_),
    .A2(_17_),
    .A3(_26_),
    .B1(_29_),
    .X(_30_)
  );
  sky130_fd_sc_hd__xor2_2 _68_ (
    .A(_28_),
    .B(_30_),
    .X(P[6])
  );
  sky130_fd_sc_hd__o211ai_2 _69_ (
    .A1(_17_),
    .A2(_18_),
    .B1(_02_),
    .C1(_04_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__and2_2 _70_ (
    .A(_19_),
    .B(_31_),
    .X(P[3])
  );
  sky130_fd_sc_hd__a22o_2 _71_ (
    .A1(B[3]),
    .A2(_08_),
    .B1(_28_),
    .B2(_30_),
    .X(P[7])
  );
  sky130_fd_sc_hd__buf_2 _72_ (
    .A(\mul_ll.pp1 ),
    .X(P[0])
  );
  sky130_fd_sc_hd__buf_2 _73_ (
    .A(\mul_ll.pp2 ),
    .X(P[1])
  );
endmodule
