/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module Sarsa_Ruido_e9_1(A, B, P);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  output [3:0] P;
  wire [3:0] P;
  sky130_fd_sc_hd__inv_2 _05_ (
    .A(B[0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__and4bb_2 _06_ (
    .A_N(A[1]),
    .B_N(B[1]),
    .C(A[0]),
    .D(B[0]),
    .X(_00_)
  );
  sky130_fd_sc_hd__a21oi_2 _07_ (
    .A1(A[1]),
    .A2(_04_),
    .B1(_00_),
    .Y(P[1])
  );
  sky130_fd_sc_hd__nand3b_2 _08_ (
    .A_N(B[0]),
    .B(B[1]),
    .C(A[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__inv_2 _09_ (
    .A(_01_),
    .Y(P[3])
  );
  sky130_fd_sc_hd__nand2b_2 _10_ (
    .A_N(B[1]),
    .B(B[0]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a31o_2 _11_ (
    .A1(A[1]),
    .A2(_01_),
    .A3(_02_),
    .B1(_00_),
    .X(P[2])
  );
  sky130_fd_sc_hd__o2bb2a_2 _12_ (
    .A1_N(B[0]),
    .A2_N(A[0]),
    .B1(B[1]),
    .B2(A[1]),
    .X(_03_)
  );
  sky130_fd_sc_hd__nor2_2 _13_ (
    .A(_00_),
    .B(_03_),
    .Y(P[0])
  );
endmodule
