/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module SarsaNada_e6(A, B, P);
  wire _0_;
  wire _1_;
  wire _2_;
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  output [3:0] P;
  wire [3:0] P;
  sky130_fd_sc_hd__nand2_2 _3_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_2_)
  );
  sky130_fd_sc_hd__and4_2 _4_ (
    .A(B[0]),
    .B(A[1]),
    .C(B[1]),
    .D(A[0]),
    .X(P[3])
  );
  sky130_fd_sc_hd__o21ba_2 _5_ (
    .A1(B[1]),
    .A2(A[0]),
    .B1_N(A[1]),
    .X(_0_)
  );
  sky130_fd_sc_hd__a21o_2 _6_ (
    .A1(B[0]),
    .A2(_0_),
    .B1(P[3]),
    .X(P[0])
  );
  sky130_fd_sc_hd__a22oi_2 _7_ (
    .A1(B[0]),
    .A2(A[1]),
    .B1(B[1]),
    .B2(A[0]),
    .Y(_1_)
  );
  sky130_fd_sc_hd__nor2_2 _8_ (
    .A(P[3]),
    .B(_1_),
    .Y(P[1])
  );
  sky130_fd_sc_hd__and3_2 _9_ (
    .A(A[1]),
    .B(B[1]),
    .C(_2_),
    .X(P[2])
  );
endmodule
