/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module SARSA_RUIDO_VENTAJA_e5(A, B, P);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  output [3:0] P;
  wire [3:0] P;
  sky130_fd_sc_hd__inv_2 _04_ (
    .A(B[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__and2_2 _05_ (
    .A(B[1]),
    .B(A[1]),
    .X(_00_)
  );
  sky130_fd_sc_hd__and4_2 _06_ (
    .A(A[0]),
    .B(B[1]),
    .C(B[0]),
    .D(A[1]),
    .X(P[3])
  );
  sky130_fd_sc_hd__a21o_2 _07_ (
    .A1(A[0]),
    .A2(_03_),
    .B1(P[3]),
    .X(P[0])
  );
  sky130_fd_sc_hd__nor2_2 _08_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand2b_2 _09_ (
    .A_N(B[0]),
    .B(A[0]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a21oi_2 _10_ (
    .A1(_00_),
    .A2(_02_),
    .B1(_01_),
    .Y(P[1])
  );
  sky130_fd_sc_hd__a21boi_2 _11_ (
    .A1(A[0]),
    .A2(B[0]),
    .B1_N(_00_),
    .Y(P[2])
  );
endmodule
