/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module mult4_SarsaNStepsRuido_e9_SarsaNStepsRuido_e9_SarsaNStepsRuido_e9_SARSA_RUIDO_e9(A, B, P);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  output [7:0] P;
  wire [7:0] P;
  sky130_fd_sc_hd__inv_2 _46_ (
    .A(B[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__inv_2 _47_ (
    .A(A[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand3_2 _48_ (
    .A(A[0]),
    .B(B[0]),
    .C(A[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_2 _49_ (
    .A(B[0]),
    .B(B[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__a21o_2 _50_ (
    .A1(B[0]),
    .A2(A[1]),
    .B1(A[0]),
    .X(_04_)
  );
  sky130_fd_sc_hd__o211a_2 _51_ (
    .A1(B[0]),
    .A2(B[1]),
    .B1(_02_),
    .C1(_04_),
    .X(P[1])
  );
  sky130_fd_sc_hd__and4_2 _52_ (
    .A(A[0]),
    .B(B[0]),
    .C(A[1]),
    .D(B[1]),
    .X(_05_)
  );
  sky130_fd_sc_hd__nand2_2 _53_ (
    .A(A[1]),
    .B(B[1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a21oi_2 _54_ (
    .A1(_02_),
    .A2(_06_),
    .B1(_05_),
    .Y(P[2])
  );
  sky130_fd_sc_hd__and3_2 _55_ (
    .A(B[0]),
    .B(A[3]),
    .C(A[2]),
    .X(_07_)
  );
  sky130_fd_sc_hd__a21oi_2 _56_ (
    .A1(B[0]),
    .A2(A[3]),
    .B1(A[2]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__and3_2 _57_ (
    .A(A[0]),
    .B(A[1]),
    .C(B[2]),
    .X(_09_)
  );
  sky130_fd_sc_hd__nor2_2 _58_ (
    .A(B[2]),
    .B(B[3]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a21oi_2 _59_ (
    .A1(A[1]),
    .A2(B[2]),
    .B1(A[0]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__or4b_2 _60_ (
    .A(_09_),
    .B(_10_),
    .C(_11_),
    .D_N(_05_),
    .X(_12_)
  );
  sky130_fd_sc_hd__o32ai_2 _61_ (
    .A1(_09_),
    .A2(_10_),
    .A3(_11_),
    .B1(_02_),
    .B2(_00_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2_2 _62_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__or4_2 _63_ (
    .A(_03_),
    .B(_07_),
    .C(_08_),
    .D(_14_),
    .X(_15_)
  );
  sky130_fd_sc_hd__o31ai_2 _64_ (
    .A1(_03_),
    .A2(_07_),
    .A3(_08_),
    .B1(_14_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__and2_2 _65_ (
    .A(_15_),
    .B(_16_),
    .X(P[3])
  );
  sky130_fd_sc_hd__nand2_2 _66_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__and4_2 _67_ (
    .A(A[0]),
    .B(A[1]),
    .C(B[2]),
    .D(B[3]),
    .X(_18_)
  );
  sky130_fd_sc_hd__nand2_2 _68_ (
    .A(A[1]),
    .B(B[3]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__mux2_1 _69_ (
    .A0(_19_),
    .A1(B[3]),
    .S(_09_),
    .X(_20_)
  );
  sky130_fd_sc_hd__nand2_2 _70_ (
    .A(B[1]),
    .B(A[3]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__mux2_1 _71_ (
    .A0(_21_),
    .A1(B[1]),
    .S(_07_),
    .X(_22_)
  );
  sky130_fd_sc_hd__nor2_2 _72_ (
    .A(_20_),
    .B(_22_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__xor2_2 _73_ (
    .A(_20_),
    .B(_22_),
    .X(_24_)
  );
  sky130_fd_sc_hd__xor2_2 _74_ (
    .A(_17_),
    .B(_24_),
    .X(_25_)
  );
  sky130_fd_sc_hd__a21o_2 _75_ (
    .A1(_12_),
    .A2(_15_),
    .B1(_25_),
    .X(_26_)
  );
  sky130_fd_sc_hd__a21oi_2 _76_ (
    .A1(B[2]),
    .A2(A[3]),
    .B1(B[3]),
    .Y(_27_)
  );
  sky130_fd_sc_hd__and3_2 _77_ (
    .A(B[2]),
    .B(A[3]),
    .C(A[2]),
    .X(_28_)
  );
  sky130_fd_sc_hd__a211o_2 _78_ (
    .A1(B[3]),
    .A2(_01_),
    .B1(_27_),
    .C1(_28_),
    .X(_29_)
  );
  sky130_fd_sc_hd__and3_2 _79_ (
    .A(B[1]),
    .B(_07_),
    .C(_18_),
    .X(_30_)
  );
  sky130_fd_sc_hd__a21oi_2 _80_ (
    .A1(B[1]),
    .A2(_07_),
    .B1(_18_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__or2_2 _81_ (
    .A(_30_),
    .B(_31_),
    .X(_32_)
  );
  sky130_fd_sc_hd__xor2_2 _82_ (
    .A(_29_),
    .B(_32_),
    .X(_33_)
  );
  sky130_fd_sc_hd__a31o_2 _83_ (
    .A1(B[2]),
    .A2(A[2]),
    .A3(_24_),
    .B1(_23_),
    .X(_34_)
  );
  sky130_fd_sc_hd__and2_2 _84_ (
    .A(_33_),
    .B(_34_),
    .X(_35_)
  );
  sky130_fd_sc_hd__xor2_2 _85_ (
    .A(_33_),
    .B(_34_),
    .X(_36_)
  );
  sky130_fd_sc_hd__and2b_2 _86_ (
    .A_N(_26_),
    .B(_36_),
    .X(_37_)
  );
  sky130_fd_sc_hd__xnor2_2 _87_ (
    .A(_26_),
    .B(_36_),
    .Y(P[5])
  );
  sky130_fd_sc_hd__nor2_2 _88_ (
    .A(_35_),
    .B(_37_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__and3_2 _89_ (
    .A(B[3]),
    .B(A[3]),
    .C(_17_),
    .X(_39_)
  );
  sky130_fd_sc_hd__o21bai_2 _90_ (
    .A1(_29_),
    .A2(_31_),
    .B1_N(_30_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__and2_2 _91_ (
    .A(_39_),
    .B(_40_),
    .X(_41_)
  );
  sky130_fd_sc_hd__nor2_2 _92_ (
    .A(_39_),
    .B(_40_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__or2_2 _93_ (
    .A(_41_),
    .B(_42_),
    .X(_43_)
  );
  sky130_fd_sc_hd__o21ba_2 _94_ (
    .A1(_35_),
    .A2(_37_),
    .B1_N(_43_),
    .X(_44_)
  );
  sky130_fd_sc_hd__xor2_2 _95_ (
    .A(_38_),
    .B(_43_),
    .X(P[6])
  );
  sky130_fd_sc_hd__a211o_2 _96_ (
    .A1(B[3]),
    .A2(_28_),
    .B1(_41_),
    .C1(_44_),
    .X(P[7])
  );
  sky130_fd_sc_hd__nand3_2 _97_ (
    .A(_12_),
    .B(_15_),
    .C(_25_),
    .Y(_45_)
  );
  sky130_fd_sc_hd__and2_2 _98_ (
    .A(_26_),
    .B(_45_),
    .X(P[4])
  );
  sky130_fd_sc_hd__conb_1 _99_ (
    .LO(P[0])
  );
endmodule
