/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module SARSANSTEPS_VENTAJA_e7(A, B, P);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  output [3:0] P;
  wire [3:0] P;
  sky130_fd_sc_hd__xnor2_2 _04_ (
    .A(B[0]),
    .B(A[0]),
    .Y(P[0])
  );
  sky130_fd_sc_hd__mux2_1 _05_ (
    .A0(A[0]),
    .A1(A[1]),
    .S(B[0]),
    .X(_00_)
  );
  sky130_fd_sc_hd__and2b_2 _06_ (
    .A_N(B[1]),
    .B(B[0]),
    .X(_01_)
  );
  sky130_fd_sc_hd__and2b_2 _07_ (
    .A_N(B[0]),
    .B(B[1]),
    .X(_02_)
  );
  sky130_fd_sc_hd__nand2_2 _08_ (
    .A(A[0]),
    .B(A[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__o31a_2 _09_ (
    .A1(_01_),
    .A2(_02_),
    .A3(_03_),
    .B1(_00_),
    .X(P[1])
  );
  sky130_fd_sc_hd__o211a_2 _10_ (
    .A1(_02_),
    .A2(_03_),
    .B1(B[1]),
    .C1(A[1]),
    .X(P[2])
  );
  sky130_fd_sc_hd__and4_2 _11_ (
    .A(B[0]),
    .B(A[0]),
    .C(B[1]),
    .D(A[1]),
    .X(P[3])
  );
endmodule
