/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module SARSA_RUIDO_VENTAJA_e5(A, B, P);
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  output [3:0] P;
  wire [3:0] P;
  wire pp1;
  sky130_fd_sc_hd__and2_2 _0_ (
    .A(A[1]),
    .B(B[1]),
    .X(P[2])
  );
  sky130_fd_sc_hd__xor2_2 _1_ (
    .A(A[1]),
    .B(B[1]),
    .X(P[1])
  );
  sky130_fd_sc_hd__and2b_2 _2_ (
    .A_N(B[1]),
    .B(A[0]),
    .X(pp1)
  );
  sky130_fd_sc_hd__conb_1 _3_ (
    .LO(P[3])
  );
  sky130_fd_sc_hd__buf_2 _4_ (
    .A(pp1),
    .X(P[0])
  );
endmodule
