/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module SarsaNada_e6(A, B, P);
  wire _0_;
  wire _1_;
  wire _2_;
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  output [3:0] P;
  wire [3:0] P;
  sky130_fd_sc_hd__a21bo_2 _3_ (
    .A1(B[1]),
    .A2(A[0]),
    .B1_N(A[1]),
    .X(_2_)
  );
  sky130_fd_sc_hd__and2_2 _4_ (
    .A(B[0]),
    .B(_2_),
    .X(P[0])
  );
  sky130_fd_sc_hd__nand4_2 _5_ (
    .A(B[1]),
    .B(B[0]),
    .C(A[1]),
    .D(A[0]),
    .Y(_0_)
  );
  sky130_fd_sc_hd__inv_2 _6_ (
    .A(_0_),
    .Y(P[3])
  );
  sky130_fd_sc_hd__a22o_2 _7_ (
    .A1(B[0]),
    .A2(A[1]),
    .B1(A[0]),
    .B2(B[1]),
    .X(_1_)
  );
  sky130_fd_sc_hd__and2_2 _8_ (
    .A(_0_),
    .B(_1_),
    .X(P[1])
  );
  sky130_fd_sc_hd__and3_2 _9_ (
    .A(B[1]),
    .B(A[1]),
    .C(_0_),
    .X(P[2])
  );
endmodule
