// Auto-generated by OpenLane
module mult4_SARSA_RUIDO_e9_SARSA_RUIDO_e9_SarsaNada_e6_SARSA_RUIDO_e9(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[3:0] A,
  input[3:0] B,
  output[7:0] P
);
endmodule
